services:
  backend:
    image: task-be
    build:
      context: TaskApi/TaskApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=appdb;Username=postgres;Password=secret
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
  frontend:
    image: task-fe
    build:
      context: TaskFe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:

    
